version: '3'

services:
  reverse-proxy:
    network_mode: host
    image: nginx:latest
    ports:
      - "80:80"
    configs:
      - source: nginx.conf
        target: /etc/nginx/

configs:
  nginx.conf:
    file: ./config/nginx.conf